### ISSUE TITLE
Simple stereo equalization?

### ISSUE THREAD

**Issue by PaulWieland** [jrubinstein/raspiDSP#1]
I found your repo while looking for a solution to apply digital signal filtering on my rpi 4. Long story short, I want to be able to define ~12 to 20 band, gain & q parameters for a stereo (two channel) signal. 

It seems you are applying a single equalization band [with this config line](https://github.com/jrubinstein/raspiDSP/blob/ae48556ef06a410ac83ceb62f059d8770b2d1d43/alsa%20configuration%20asoundrc-experimental2.cpp#L30), but I'm having a hard figuring out how to simplify your configuration for my own purpose.

my aplay -L output looks like this (no external sound card, outputting audio through the 3.5mm headphone jack at the moment):

```
aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
dmix:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample mixing device
dsnoop:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample snooping device
hw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct hardware device without any conversions
plughw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Hardware device with all software conversions
```

The EQ (Generated by Room EQ Wizard) I want to apply is:

```
Fc    53.1 Hz  Gain   6.0 dB  Q 8.530
Fc    59.1 Hz  Gain  -8.2 dB  Q 3.793
Fc    69.7 Hz  Gain  -6.0 dB  Q 9.912
Fc     126 Hz  Gain  -3.5 dB  Q 18.191
Fc     305 Hz  Gain   6.0 dB  Q 5.000
Fc     325 Hz  Gain  -5.4 dB  Q 5.000
Fc     509 Hz  Gain  -3.3 dB  Q 5.000
Fc     685 Hz  Gain  -4.3 dB  Q 5.000
Fc    1433 Hz  Gain   6.0 dB  Q 5.000
Fc    1501 Hz  Gain  -8.2 dB  Q 5.000
Fc    1780 Hz  Gain  -5.8 dB  Q 5.000
Fc    2017 Hz  Gain  -5.8 dB  Q 5.000
Fc    2231 Hz  Gain  -5.4 dB  Q 5.000
Fc    3265 Hz  Gain  -8.3 dB  Q 5.000
Fc    4985 Hz  Gain  -4.1 dB  Q 5.000
```

Is this possible to do?

**Comment by jrubinstein** [comment]
you can have as many bands as you like!  (okay as many as the pi 4's
processor can handle). If you are sticking with 2 channel and/or not using
HDMI, then you don't have to do any kernel changes.
If you are using ACDf
then you can have a .asoundrc or asound.conf like
0{
label ACDf
policy none
input.bindings.0 "Input"
output.bindings.0 "Output"
input { controls [26 1 6 53.1 8.53 1 1] }#parametric digital eq cutting 6db
at 164hz with q of 4
}
1{
label ACDf
policy none
input.bindings.0 "Input"
output.bindings.0 "Output"
input { controls [26 1 -8.2 59.1 3.793 1 1] }#parametric digital eq cutting
6db at 164hz with q of 4
}
and keep going.
make sense?

**Comment by PaulWieland** [comment]
Yeah, that makes sense and sounds promising.

I installed ladspa-skd and built ACDF_v3, so I have `/airplay2/ACDF_v3/ACDf.so` now.
I believe something is wrong with the way I am trying to load the plugin.

Here's my .asoundrc:
```
pcm.equalizer {
	type ladspa
	path "/airplay2/ACDF_v3"
	channels 2

	slave {
		pcm "plughw:0"
	}

	plugins {
		0 {
			label ACDf
			policy none
			input.bindings.0 "Input"
			output.bindings.0 "Output"
			input { controls [26 1 6 453 -13.4 1 1 1] }
		}
	}
}
pcm.!default {
	type plug
	slave { pcm equalizer }
}
```

`speaker-test` is outputting this error:

```
ALSA lib pcm_ladspa.c:1278:(snd_pcm_ladspa_parse_controls) Unable to find an control port (7)
Playback open error: -22,Invalid argument
```

Seems to be kind of obscure as I am not finding any hints on google.

**Comment by jrubinstein** [comment]
you have an extra "1" in controls - there should only be 7.
Type, polarity, dbgain, frequency, Qp, fz, qz
you only need the last two if you're doing a 28-biquad filter.
it also looks like you have a qp of -13.4, and I don't think it likes
negative q values.
finally, I think you need to map your ladspa directory, not the
download/install directory /airplay2/ACDF_v3
you can install to /usr/lib/ladspa or /usr/local/lib/ladspa (or both)
even if you installed to /airplay2/ACDF_v3, i'd go back and install to
/usr/lib/ladspa because that's where the rest of the ladspa filters live.

last piece of advice is that I'd start with a crossover so you can hear if
there's a difference to ensure it's working properly.

make sure to read the ACDf usage notes as well as the readme for
installation instructions. Charlie's got good stuff in there :)

**Comment by PaulWieland** [comment]
I just found the instructions for the ACDf plugin :)

I'm getting closer. I have (what sounds like) equalized audio coming out one channel and a rapid ticking noise coming out of the other channel. 

EDIT:

`speaker-test -c 2` - static on left channel and nothing on the right

**Comment by PaulWieland** [comment]
Got it now. I had a typo in my output binding for channel 1. I documented what I did for a simple stereo EQ on [dsp.stackexchange.com](https://dsp.stackexchange.com/questions/74632/equalizing-audio-under-linux-raspberry-pi/74760#74760)

Thank you so much for the assistance!
